steps:
  build-dry-run:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/${CI_REPO_NAME%%-service}
      dry-run: true
      purge: true
when:
  - event: pull_request
